-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cliente
(
    id_usuario integer NOT NULL,
    nombre text COLLATE pg_catalog."default" NOT NULL,
    apellidos text COLLATE pg_catalog."default" NOT NULL,
    correo text COLLATE pg_catalog."default" NOT NULL,
    dni text COLLATE pg_catalog."default" NOT NULL,
    direccion text COLLATE pg_catalog."default" NOT NULL,
    username text COLLATE pg_catalog."default" NOT NULL,
    password text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "UsuarioConvencional_pkey" PRIMARY KEY (id_usuario)
);

CREATE TABLE IF NOT EXISTS public.hostelero
(
    id_usuario integer NOT NULL,
    nombre text COLLATE pg_catalog."default" NOT NULL,
    apellidos text COLLATE pg_catalog."default" NOT NULL,
    correo text COLLATE pg_catalog."default" NOT NULL,
    password text COLLATE pg_catalog."default" NOT NULL,
    id_restaurante integer NOT NULL,
    CONSTRAINT "UsuarioRestaurante_pkey" PRIMARY KEY (id_usuario)
);

CREATE TABLE IF NOT EXISTS public.pais
(
    id_pais integer NOT NULL,
    nombre text COLLATE pg_catalog."default" NOT NULL,
    bandera text COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Pais_pkey" PRIMARY KEY (id_pais)
);

CREATE TABLE IF NOT EXISTS public.pedido
(
    id_pedido integer NOT NULL,
    fecha date NOT NULL,
    id_usuario integer NOT NULL,
    precio numeric NOT NULL,
    CONSTRAINT "Pedido_pkey" PRIMARY KEY (id_pedido)
);

CREATE TABLE IF NOT EXISTS public.producto
(
    id_producto integer NOT NULL,
    nombre text COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    precio numeric NOT NULL,
    id_pais integer NOT NULL,
    id_restaurante integer NOT NULL,
    imagen text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Producto_pkey" PRIMARY KEY (id_producto)
);

CREATE TABLE IF NOT EXISTS public.restaurante
(
    id_restaurante integer NOT NULL,
    direccion text COLLATE pg_catalog."default" NOT NULL,
    nombre text COLLATE pg_catalog."default" NOT NULL,
    id_pais integer NOT NULL,
    imagen text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Restaurante_pkey" PRIMARY KEY (id_restaurante)
);

ALTER TABLE IF EXISTS public.hostelero
    ADD CONSTRAINT "UsuarioRestaurante_ID_Restaurante_fkey" FOREIGN KEY (id_restaurante)
    REFERENCES public.restaurante (id_restaurante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pedido
    ADD CONSTRAINT "Pedido_ID_Usuario_fkey" FOREIGN KEY (id_usuario)
    REFERENCES public.cliente (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.producto
    ADD CONSTRAINT "Producto_ID_País_fkey" FOREIGN KEY (id_pais)
    REFERENCES public.pais (id_pais) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.producto
    ADD CONSTRAINT "Producto_ID_Restaurante_fkey" FOREIGN KEY (id_restaurante)
    REFERENCES public.restaurante (id_restaurante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.restaurante
    ADD CONSTRAINT "Restaurante_ID_Pais_fkey" FOREIGN KEY (id_pais)
    REFERENCES public.pais (id_pais) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;