-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Pais"
(
    "ID_País" integer NOT NULL,
    "Nombre" text COLLATE pg_catalog."default" NOT NULL,
    "Bandera" text COLLATE pg_catalog."default" NOT NULL,
    "Descripcion" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Pais_pkey" PRIMARY KEY ("ID_País")
);

CREATE TABLE IF NOT EXISTS public."Pedido"
(
    "ID_Pedido" integer NOT NULL,
    "Fecha" date NOT NULL,
    "ID_Producto" integer NOT NULL,
    "ID_Usuario" integer NOT NULL,
    CONSTRAINT "Pedido_pkey" PRIMARY KEY ("ID_Pedido")
);

CREATE TABLE IF NOT EXISTS public."Producto"
(
    "ID_Producto" integer NOT NULL,
    "Nombre" text COLLATE pg_catalog."default" NOT NULL,
    "Descripcion" text COLLATE pg_catalog."default",
    "Precio" numeric NOT NULL,
    "ID_País" integer NOT NULL,
    "ID_Restaurante" integer NOT NULL,
    CONSTRAINT "Producto_pkey" PRIMARY KEY ("ID_Producto")
);

CREATE TABLE IF NOT EXISTS public."Restaurante"
(
    "ID_Restaurante" integer NOT NULL,
    "Direccion" text COLLATE pg_catalog."default" NOT NULL,
    "Nombre" text COLLATE pg_catalog."default" NOT NULL,
    "ID_Pais" integer NOT NULL,
    CONSTRAINT "Restaurante_pkey" PRIMARY KEY ("ID_Restaurante")
);

CREATE TABLE IF NOT EXISTS public."UsuarioConvencional"
(
    "ID_Usuario" integer NOT NULL,
    "Nombre" text COLLATE pg_catalog."default" NOT NULL,
    "Apellidos" text COLLATE pg_catalog."default" NOT NULL,
    "Correo" text COLLATE pg_catalog."default" NOT NULL,
    "DNI" text COLLATE pg_catalog."default" NOT NULL,
    "Dirección" text COLLATE pg_catalog."default" NOT NULL,
    "UserName" text COLLATE pg_catalog."default" NOT NULL,
    "Password" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "UsuarioConvencional_pkey" PRIMARY KEY ("ID_Usuario")
);

CREATE TABLE IF NOT EXISTS public."UsuarioRestaurante"
(
    "ID_Usuario" integer NOT NULL,
    "Nombre" text COLLATE pg_catalog."default" NOT NULL,
    "Apellidos" text COLLATE pg_catalog."default" NOT NULL,
    "UserName" text COLLATE pg_catalog."default" NOT NULL,
    "Password" text COLLATE pg_catalog."default" NOT NULL,
    "ID_Restaurante" integer NOT NULL,
    CONSTRAINT "UsuarioRestaurante_pkey" PRIMARY KEY ("ID_Usuario")
);

ALTER TABLE IF EXISTS public."Pedido"
    ADD CONSTRAINT "Pedido_ID_Producto_fkey" FOREIGN KEY ("ID_Producto")
    REFERENCES public."Producto" ("ID_Producto") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Pedido"
    ADD CONSTRAINT "Pedido_ID_Usuario_fkey" FOREIGN KEY ("ID_Usuario")
    REFERENCES public."UsuarioConvencional" ("ID_Usuario") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Producto"
    ADD CONSTRAINT "Producto_ID_País_fkey" FOREIGN KEY ("ID_País")
    REFERENCES public."Pais" ("ID_País") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Producto"
    ADD CONSTRAINT "Producto_ID_Restaurante_fkey" FOREIGN KEY ("ID_Restaurante")
    REFERENCES public."Restaurante" ("ID_Restaurante") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Restaurante"
    ADD CONSTRAINT "Restaurante_ID_Pais_fkey" FOREIGN KEY ("ID_Pais")
    REFERENCES public."Pais" ("ID_País") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."UsuarioRestaurante"
    ADD CONSTRAINT "UsuarioRestaurante_ID_Restaurante_fkey" FOREIGN KEY ("ID_Restaurante")
    REFERENCES public."Restaurante" ("ID_Restaurante") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;