update producto set imagen = 'https://i.postimg.cc/wM1Rg2V5/pngwing-com-1.png' where id_producto = 1;
update producto set imagen = 'https://i.postimg.cc/0NcXM5Yk/pngwing-com-2.png' where id_producto = 2;
update producto set imagen = 'https://i.postimg.cc/gkX0qtTF/pngwing-com-3.png' where id_producto = 3;
update producto set imagen = 'https://i.postimg.cc/QNnt7ZSJ/pngwing-com-4.png' where id_producto = 4;
update producto set imagen = 'https://i.postimg.cc/8c3zgLs0/pngwing-com-5.png' where id_producto = 5;
update producto set imagen = 'https://i.postimg.cc/NFLjndGX/pngwing-com-6.png' where id_producto = 6;
update producto set imagen = 'https://i.postimg.cc/SNBxZLBX/pngwing-com-7.png' where id_producto = 7;
update producto set imagen = 'https://i.postimg.cc/sg5DbQzT/pngwing-com-8.png' where id_producto = 8;
update producto set imagen = 'https://i.postimg.cc/MGbHfcrn/pngwing-com-9.png' where id_producto = 9;
update producto set imagen = 'https://i.postimg.cc/rmVm18vQ/pngwing-com-10.png' where id_producto = 10;
update producto set imagen = 'https://i.postimg.cc/fRdJZqcj/pngwing-com-11.png' where id_producto = 11;
update producto set imagen = 'https://i.postimg.cc/CKVdKCJy/pngwing-com-12.png' where id_producto = 12;
update producto set imagen = 'https://i.postimg.cc/J4vGfCkz/pngwing-com-13.png' where id_producto = 13;
update producto set imagen = 'https://i.postimg.cc/GhH4gm9f/pngwing-com-14.png' where id_producto = 14;
update producto set imagen = 'https://i.postimg.cc/sx0vftHK/pngwing-com-15.png' where id_producto = 15;
update producto set imagen = 'https://i.postimg.cc/C17RXZj3/pngwing-com-16.png' where id_producto = 16;
update producto set imagen = 'https://i.postimg.cc/4y3YgJPm/pngwing-com-17.png' where id_producto = 17;
update producto set imagen = 'https://i.postimg.cc/sXsBTPZP/pngwing-com-18.png' where id_producto = 18;
update producto set imagen = 'https://i.postimg.cc/v8P1vV89/pngwing-com-19.png' where id_producto = 19;
update producto set imagen = 'https://i.postimg.cc/3N92XSSD/pngwing-com-37.png' where id_producto = 20;
update producto set imagen = 'https://i.postimg.cc/43CH9RfS/pngwing-com-21.png' where id_producto = 21;
update producto set imagen = 'https://i.postimg.cc/ZKRNkLsV/pngwing-com-22.png' where id_producto = 22;
update producto set imagen = 'https://i.postimg.cc/9Qwq0Qh9/pngwing-com-23.png' where id_producto = 23;
update producto set imagen = 'https://i.postimg.cc/xjgmFZ5X/pngwing-com-24.png' where id_producto = 24;
update producto set imagen = 'https://i.postimg.cc/bvQD0VdN/pngwing-com-25.png' where id_producto = 25;
update producto set imagen = 'https://i.postimg.cc/bvQD0VdN/pngwing-com-25.png' where id_producto = 26;
update producto set imagen = 'https://i.postimg.cc/3RFGhfHb/pngwing-com-27.png' where id_producto = 27;
update producto set imagen = 'https://i.postimg.cc/zvdRbLvC/pngwing-com-28.png' where id_producto = 28;
update producto set imagen = 'https://i.postimg.cc/rmk4vX7r/pngwing-com-29.png' where id_producto = 29;
update producto set imagen = 'https://i.postimg.cc/zfWWtX2N/pngwing-com-30.png' where id_producto = 30;
update producto set imagen = 'https://i.postimg.cc/8P06TrqD/pngwing-com-31.png' where id_producto = 31;
update producto set imagen = 'https://i.postimg.cc/HsZQjN8q/pngwing-com-32.png' where id_producto = 32;
update producto set imagen = 'https://i.postimg.cc/rFF1VTsG/pngwing-com-33.png' where id_producto = 33;
update producto set imagen = 'https://i.postimg.cc/6p8CZhdy/pngwing-com-34.png', id_producto = 34 where id_producto = 35;
update producto set imagen = 'https://i.postimg.cc/RCT1xhSV/pngwing-com-35.png', id_producto = 35 where id_producto = 36;
update producto set imagen = 'https://i.postimg.cc/26QQ68nG/pngwing-com-36.png', id_producto = 36 where id_producto = 37;
update producto set imagen = 'https://i.postimg.cc/3N92XSSD/pngwing-com-37.png', id_producto = 37 where id_producto = 38;
update producto set imagen = 'https://i.postimg.cc/TwMjfW5h/pngwing-com-38.png', id_producto = 38 where id_producto = 39;
update producto set imagen = 'https://i.postimg.cc/t4ctvcX3/pngwing-com-39.png', id_producto = 39 where id_producto = 40;
update producto set imagen = 'https://i.postimg.cc/rptGB9mv/pngwing-com-40.png', id_producto = 40 where id_producto = 41;
update producto set imagen = 'https://i.postimg.cc/D07qbkgT/pngwing-com-41.png', id_producto = 41 where id_producto = 42;
update producto set imagen = 'https://i.postimg.cc/7ZhnV4yP/pngwing-com-42.png', id_producto = 42 where id_producto = 43;
update producto set imagen = 'https://i.postimg.cc/dVgrjTBn/pngwing-com-43.png', id_producto = 43 where id_producto = 44;
update producto set imagen = 'https://i.postimg.cc/BQMCH6kw/pngwing-com-44.png', id_producto = 44 where id_producto = 45;
update producto set imagen = 'https://i.postimg.cc/TYR9Km7D/pngwing-com-45.png', id_producto = 45 where id_producto = 46;
update producto set imagen = 'https://i.postimg.cc/8kd4kwHG/pngwing-com-46.png', id_producto = 46 where id_producto = 47;
update producto set imagen = 'https://i.postimg.cc/mk4SNFTK/pngwing-com-47.png', id_producto = 47 where id_producto = 48;
update producto set imagen = 'https://i.postimg.cc/QCqJ6xtC/pngwing-com-48.png', id_producto = 48 where id_producto = 49;
update producto set imagen = 'https://i.postimg.cc/g0fsjTQz/pngwing-com-49.png', id_producto = 49 where id_producto = 50;
update producto set imagen = 'https://i.postimg.cc/B6HgKCfx/pngwing-com-50.png', id_producto = 50 where id_producto = 51;
update producto set imagen = 'https://i.postimg.cc/PqLKtj6V/pngwing-com-51.png', id_producto = 51 where id_producto = 52;
update producto set imagen = 'https://i.postimg.cc/yYBf02dW/pngwing-com-52.png', id_producto = 52 where id_producto = 53;
update producto set imagen = 'https://i.postimg.cc/650Mcz2c/pngwing-com-53.png', id_producto = 53 where id_producto = 54;
update producto set imagen = 'https://i.postimg.cc/Gmmq5YvC/pngwing-com-54.png', id_producto = 54 where id_producto = 55;
update producto set imagen = 'https://i.postimg.cc/762BNk0J/pngwing-com-55.png', id_producto = 55 where id_producto = 56;
update producto set imagen = 'https://i.postimg.cc/7PSsGqqp/pngwing-com-56.png', id_producto = 56 where id_producto = 57;
update producto set imagen = 'https://i.postimg.cc/SRLDwfZy/pngwing-com-57.png', id_producto = 57 where id_producto = 58;
update producto set imagen = 'https://i.postimg.cc/DzDjsZJK/pngwing-com-58.png', id_producto = 58 where id_producto = 59;
update producto set imagen = 'https://i.postimg.cc/L5FxCb3C/pngwing-com-59.png', id_producto = 59 where id_producto = 60;
update producto set imagen = 'https://i.postimg.cc/rwfYVgqs/pngwing-com-60.png', id_producto = 60 where id_producto = 61;